
spring:
  datasource:
    url: jdbc:mysql://8.140.26.76:3306/test?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    #为了防止中文乱码，在URL中默认添加了?useUnicode=true&characterEncoding=UTF-8来使用UTF8编码，
    #&allowMultiQueries=true表示支持批量更新，因为我的电脑时区紊乱，无法启动项目，因此需要加&serverTimezone=GMT%2B8
    username: root
    password: mimamima
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    user:
      name: user
      password: $2a$10$fJdE/FgcFKMSYIF/QxPZcOBHzS0i7kf/7q5WCxbEWs45Y4.39gQAO  # 这是123456加密后的密文 人麻了

server:
  port: 8080

#mybatis-plus配置
mybatis-plus:
  #配置Mapper映射文件
  mapper-locations: classpath:/mapper/*.xml
  # 配置Mybatis数据返回类型别名（默认别名为类名）
  type-aliases-package: com.xietong.model.entity
  configuration:
    # 自动驼峰命名
    map-underscore-to-camel-case: true

#配置控制台打印日志Debug
logging:
  level:
    com.jd.mapper: debug


xietong:
  jwt:
    header: Authorization
    expire: 86400 #秒（一天）
    secret: r6tjfiy7rht565grh2d14r34aq32n0ffowgo94rhsjn2s5zeh4r8h5d3ss8f5sloen54975354nz #够64个字符位就行

